import Head from "next/head";
import Slideshow from "../components/slideshow/slideshow";
import styles from "../styles/Home.module.css";

const slides = [
	"/uploads/img (1).jpg",
	"/uploads/img (2).jpg",
	"/uploads/img (3).jpg",
	"/uploads/img (4).jpg",
];

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Slideshow slides={slides} duration={2000} time={8000} />
			</main>
		</div>
	);
}
